version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - ntw

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    depends_on:
      - postgres
    networks:
      - ntw

volumes:
  postgres-data:

networks:
  ntw:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.1.0/24
